# Generated by Django 5.2.7 on 2025-10-07 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(default='000.000.000-00', max_length=14, unique=True, verbose_name='CPF'),
            preserve_default=False,
        ),
    ]
