# Generated by Django 5.2.7 on 2025-10-09 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_pessoa_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastomensal',
            name='descricao',
            field=models.CharField(default='', max_length=200, verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gastomensal',
            name='banco',
            field=models.CharField(choices=[('Itau', 'Itaú'), ('Bradesco', 'Bradesco'), ('Santander', 'Santander'), ('Nubank', 'Nubank')], max_length=50, verbose_name='Banco'),
        ),
    ]
