# Generated by Django 5.2.7 on 2025-10-13 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_gastomensal_descricao_alter_gastomensal_banco'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banco',
        ),
        migrations.AlterField(
            model_name='gastomensal',
            name='banco',
            field=models.CharField(choices=[('Itau', 'Itaú'), ('Bradesco', 'Bradesco'), ('Santander', 'Santander'), ('Nubank', 'Nubank'), ('Outro', 'Outro')], max_length=50, verbose_name='Banco'),
        ),
    ]
