# Generated by Django 5.2.7 on 2025-10-16 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_banco_alter_gastomensal_banco'),
    ]

    operations = [
        migrations.CreateModel(
            name='GanhoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('banco', models.CharField(choices=[('Itau', 'Itaú'), ('Bradesco', 'Bradesco'), ('Santander', 'Santander'), ('Nubank', 'Nubank'), ('Outro', 'Outro')], max_length=50, verbose_name='Banco')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('mes', models.DateField(verbose_name='Mês e Ano')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor ganho')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ganhos', to='core.pessoa')),
            ],
            options={
                'verbose_name': 'Ganho Mensal',
                'verbose_name_plural': 'Ganhos Mensais',
                'ordering': ['mes'],
            },
        ),
    ]
